version: '3.8'

services:
  water-microservice:
    image: water-microservice:latest
    ports:
      - "8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27018
      SPRING_DATA_MONGODB_DATABASE: water
      SPRING_DATA_MONGODB_AUTHENTICATION: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      RABBITMQ_WATER_QUEUE_NAME: water.notification.queue
      RABBITMQ_EXCHANGE_NAME: notification.exchange
      RABBITMQ_WATER_ROUTING_KEY: water.queue.user.notification
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server:8761/eureka/
    depends_on:
      - mongodb
    networks:
      - environment-pollution-network

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - type: bind
        source: Documents/pollution/water-db
        target: /pollution/water-db
    networks:
      - environment-pollution-network

networks:
  environment-pollution-network:
    external: true
    name: project_environment-pollution-network
